name: time_sense
description: Boost productivity with TimeSense app, a tool for managing tasks and staying focused
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  circular_countdown_timer: ^0.2.3
  provider: ^6.0.5
  sqflite: ^2.3.0
  wakelock: ^0.6.2
  equatable: ^2.0.0
  uuid: ^4.0.0
  flutter_phoenix: ^1.1.1
  intl: ^0.18.1
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.2
  flutter_native_timezone_updated_gradle: ^2.0.3
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  calendar_date_picker2: ^0.5.3
  flutter_image_compress: ^2.1.0

flutter_native_splash:
  color: '#121214'
  image: 'assets/logo/app-logo.png'
  android: true

flutter_launcher_icons:
  image_path: 'assets/logo/app-logo.png'
  android: 'launcher_icon'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/logo/app-logo.png'
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf